default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: splatoon_enemy_visualizer_front_development

test:
  <<: *default
  database: splatoon_enemy_visualizer_front_test

production:
  <<: *default
  database: splatoon_enemy_visualizer_front_production
  username: splatoon_enemy_visualizer
  password: <%= ENV['SPLATOON_ENEMY_VISUALIZER_DATABASE_PASSWORD'] %>
